title: Febria Anisaningrum
email: febria@example.com
description: 'Belajar dan Bekerja'
baseurl: "" # gunakan "" jika pakai root domain GitHub Pages
url: "https://febriaanisa.github.io"
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
