title: Febria Anisaningrum
email: febriaanisaningrum31@gmail.com
description: 'Belajar dan Bekerja'
baseurl: "/profil" # gunakan "" jika pakai root domain GitHub Pages
url: "https://febriaanisa.github.io/profil"
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
